In [ ]:
import numpy as np

In [ ]:
1. A list is a collection of values
2. Inorder to create a list, the collection of values, need to be surrounded by square brackets
3. In the collection, we can have any number of values. However, if you have multiple values(more than 1) in the collection, then those values need to separated by a comma.
4. A list can contain any types of values
5. All the values in the list, have 2 indexes (positive, negative) associated with it

Array
1. A Array is a collection of values
2. Inorder to create a array, the collection of values, need to be surrounded by square or curved brackets
3. In the collection, we can have any number of values. However, if you have multiple values(more than 1) in the collection, then those values need to separated by a comma.
4. A Array can contain a single type of a value. If you store values of different types, then those values will be converted to the same type. THis type conversion will only apply when all the values are of primitive types
5. All the values in the array, have 2 indexes (positive, negative) associated with it

In [ ]:
a=np.array((11,22,33))

In [ ]:
type(a)

numpy.ndarray

In [ ]:
len(a)

3

In [ ]:
a=np.array([11,22,33])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
len(a)

3

In [ ]:
b=np.array([4,67.8])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b

array([ 4. , 67.8])

In [ ]:
c=np.array([56,89.0,"abc"])

In [ ]:
type(c)

numpy.ndarray

In [ ]:
c

array(['56', '89.0', 'abc'], dtype='<U32')

In [ ]:
d=np.array([True, 89.8])

In [ ]:
type(d)

numpy.ndarray

In [ ]:
d

array([ 1. , 89.8])

In [ ]:
e=np.array([4,78.0,[1,2,3]])

In [ ]:
type(e)

numpy.ndarray

In [ ]:
len(e)

3

In [ ]:
e

array([4, 78.0, list([1, 2, 3])], dtype=object)

In [ ]:
a=np.array([11,22,33,44,55])

# subset values in a array

In [ ]:
a

array([11, 22, 33, 44, 55])

In [ ]:
syntax for list---- listReference[index]

syntax for array--- arrayReference[index]

In [ ]:
a[2]

33

In [ ]:
a[-3]

33

In [ ]:
a[3]

44

In [ ]:
a[-2]

44

In [ ]:
a[[0,4]]

array([11, 55])

In [ ]:
a[[0,-1]]

array([11, 55])

In [ ]:
syntax for array--- arrayReference[index]

In [ ]:
a[[1,3]]

array([22, 44])

In [ ]:
a[[0,1,2,3,4]]

array([11, 22, 33, 44, 55])

1. When we want to get multiple consecutive values from a list, we will have to use slicing.
2. When we want to use slicing with indexes, then the value at the firstSpecifiedIndex is included, while the value at the last specified index is not included. SLicing will only include values uptil the index, that is previous to the LastSpecifiedIndex, that is closest to the lastSpecified index, and also it should be within the array
3. If we leave out the FirstSpecifiedIndex, then python will assume that you want to start from the beginning. On the other hand, if you leave out the LastSpecifiedIndex, then python will assume that you want to go uptil the end

In [ ]:
syntax for slicing a list---- listReference[FirstSpecifiedIndex:LastSpecifiedIndex]

syntax for slicing a array---- arrayReference[FirstSpecifiedIndex:LastSpecifiedIndex]

In [ ]:
a

array([11, 22, 33, 44, 55])

In [ ]:
a[0:]

array([11, 22, 33, 44, 55])

In [ ]:
a

array([11, 22, 33, 44, 55])

In [ ]:
a[0:3]

array([11, 22, 33])

Similarities:
1. A list is a collection of values, just like that a array is also a collection of values
2. A list can contain any number of values, just like that a array can also contain any number of values

Difference:
1. A list can contain any type of a value, whereas a array can only contain a single type of a value
2. You cannot do mathemtical operations on the values stored inside of a list, whereas you can do mathematical operations on the values stored inside of a array

In [ ]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [ ]:
[1,2,3] * [4,5,6]

In [ ]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [ ]:
np.array([1,2,3]) * np.array([4,5,6])

array([ 4, 10, 18])

In [ ]:
a=np.array([11,22,33,44])

In [ ]:
syntax for array--- arrayReference[index]

In [ ]:
a[2]

33

In [ ]:
a[-2]

33

In [ ]:
a[[1,3]]

array([22, 44])

In [ ]:
a[[2]]

array([33])

1. When we want to get multiple consecutive values from a list, we will have to use slicing.
2. When we want to use slicing with indexes, then the value at the firstSpecifiedIndex is included, while the value at the last specified index is not included. SLicing will only include values uptil the index, that is previous to the LastSpecifiedIndex, that is closest to the lastSpecified index, and also it should be within the array
3. If we leave out the FirstSpecifiedIndex, then python will assume that you want to start from the beginning. On the other hand, if you leave out the LastSpecifiedIndex, then python will assume that you want to go uptil the end

In [ ]:
syntax for slicing a list---- listReference[FirstSpecifiedIndex:LastSpecifiedIndex]

syntax for slicing a array---- arrayReference[FirstSpecifiedIndex:LastSpecifiedIndex]

In [ ]:
a[0:2]

array([11, 22])

In [ ]:
a[0:3]

array([11, 22, 33])

In [ ]:
a[1:3]

array([22, 33])

In [ ]:
a[[1,2]]

array([22, 33])

In [ ]:
a

array([11, 22, 33, 44])

In [ ]:
list(a)

[11, 22, 33, 44]

In [ ]:
list(67)

In [ ]:
list(67.8)

TypeError: 'float' object is not iterable

In [ ]:
list("trht")

['t', 'r', 'h', 't']

In [ ]:
b=list(56)

TypeError: 'int' object is not iterable

In [ ]:
b

[56]

# Replacing Values in a array

In [ ]:
1. In a array, you can only replace a single value with a single value
2. In a array, you can only replace multiple values with the same number of multiple values

In [ ]:
a

array([11, 22, 33, 44])

In [ ]:
a[3]

44

In [ ]:
a[3]=89

In [ ]:
a

array([11, 22, 33, 89])

In [ ]:
a[3]=89.8

In [ ]:
a

array([11, 22, 33, 89])

In [ ]:
a[3]="abc"

In [ ]:
a[3]="90"

In [ ]:
a

array([11, 22, 33, 90])

In [ ]:
a

array([11, 22, 33, 90])

In [ ]:
a=np.array([11,22,33,44])

In [ ]:
a

array([11, 22, 33, 44])

In [ ]:
a[[0,2]]

array([11, 33])

In [ ]:
a[[0,2]]=[67,89]

In [ ]:
a

array([67, 22, 89, 44])

In [ ]:
a=[67]

In [ ]:
a=[67,]

In [ ]:
a

[67]

In [ ]:
len(a)

1

In [ ]:
a=(67,)

In [ ]:
a

(67,)

In [ ]:
len(a)

1

In [ ]:
a=np.array([11,22,33,44])

In [ ]:
a[[0,2]]=[67,]

In [ ]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [ ]:
np.array([1,2,3]) + np.array([4,5])

In [ ]:
Scalar value is a single value that is capable of mutating itself according to the needs in a array

In [ ]:
np.array([1,2,3]) + np.array([4])

array([5, 6, 7])

In [ ]:
a

array([67, 22, 67, 44])

In [ ]:
a=np.array([11,22,33,44])

In [ ]:
a[[0,2]]=[67,]

In [ ]:
a

array([67, 22, 67, 44])

In [ ]:
a=np.array([11,22,33,44])

In [ ]:
a[[0,2]]=[67,67]

In [ ]:
a

array([67, 22, 67, 44])

In [ ]:
b=67,89

In [ ]:
type(b)

tuple

In [ ]:
b

(67, 89)

In [ ]:
a=np.array([11,22,33,44])

In [ ]:
a[[1,2]]=[67,89]

In [ ]:
a

array([11, 67, 89, 44])

In [ ]:
a=np.array([11,22,33,44])

In [ ]:
a[[1,2]]=67,89

In [ ]:
a

array([11, 67, 89, 44])

In [ ]:
a

array([11, 67, 89, 44])

In [ ]:
a=np.array([11,22,33,44])

In [ ]:
a

array([11, 22, 33, 44])

In [ ]:
a[1:3]

array([22, 33])

In [ ]:
a[1:3]=67,89

In [ ]:
a

array([11, 67, 89, 44])

In [ ]:
a=np.array([11,22,33,44])

In [ ]:
a[[1,2]]=67

In [ ]:
a

array([11, 67, 67, 44])

In [ ]:
a=np.array([11,22,33,44])

In [ ]:
a[[1,2]]=[67,67]

In [ ]:
a

array([11, 67, 67, 44])

In [ ]:
a

array([11, 67, 67, 44])

In [ ]:
a=np.array([11,22,33,44])

In [ ]:
a.ndim

1

# One Dimensional Array

In [ ]:
a=np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
a.ndim

2

In [ ]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

In [ ]:
a.ndim

2

In [ ]:
a=np.array([
    [1,2,3],
    [4,5,6]
])

# subset values from a 2d array

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
syntax for subsetting in a 1d array --- arrayReference[index]
syntax for subsetting in a 2d array --- arrayreference[ row,column ]

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[ 1,1 ]

5

In [ ]:
a[ 0,2 ]

3

In [ ]:
a[[0,1] ,[0,2] ]

array([1, 6])

In [ ]:
a[[0,1,0,1] ,[0,0,2,2] ]

array([1, 4, 3, 6])

1. When we want to get multiple consecutive values from a list, we will have to use slicing.
2. When we want to use slicing with indexes, then the value at the firstSpecifiedIndex is included, while the value at the last specified index is not included. SLicing will only include values uptil the index, that is previous to the LastSpecifiedIndex, that is closest to the lastSpecified index, and also it should be within the array
3. If we leave out the FirstSpecifiedIndex, then python will assume that you want to start from the beginning. On the other hand, if you leave out the LastSpecifiedIndex, then python will assume that you want to go uptil the end

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
syntax for subsetting in a 2d array --- arrayreference[ row,column ]

In [ ]:
a[ : , 0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
a[ 0:1, 0:2]

array([[1, 2]])

In [ ]:
a[ 0, 0:2]

array([1, 2])

# Replace values in a 2d array

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[ 1,2 ]

6

In [ ]:
a[ 1,2 ]=600

In [ ]:
a

array([[  1,   2,   3],
       [  4,   5, 600]])

In [ ]:
a=np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
syntax for subsetting in a 2d array --- arrayreference[ row,column ]

In [ ]:
a[[0,1] , [2,0]]

array([3, 4])

In [ ]:
a[[0,1] , [2,0]]=[300,400,500]

In [ ]:
a[[0,1] , [2,0]]=[300,400]

In [ ]:
a

array([[  1,   2, 300],
       [400,   5,   6]])